### ISSUE TITLE
文档部分无法显示golang语言定义界面

### ISSUE THREAD

**Issue by liujunminx** [apache/dubbo-website#1001]
![image](https://user-images.githubusercontent.com/39694578/144345621-985bc0b6-7821-4eb8-9371-6aa5addb87ac.png)

**Comment by jasondeng1997** [comment]
已经改了

**Comment by jasondeng1997** [comment]
改好了，这个可以关了

**Comment by jasondeng1997** [comment]
改好了，这个可以关了
