### ISSUE TITLE
Dubbo2.7文档 用法示例-粘滞连接 有个英文单词拼写错误

### ISSUE THREAD

**Issue by cxmshine** [apache/dubbo-website#1019]
![image](https://user-images.githubusercontent.com/37296677/147477316-82fb75b2-462d-4b2d-b6e4-82d9ea8196a8.png)
<dubbo:mothod name="sayHello" sticky="true" /> 中的 `mothod` 拼写有误，应改为`method`，望采纳，谢谢。文档很赞。

**Comment by cxmshine** [comment]
附上链接 https://dubbo.apache.org/zh/docs/v2.7/user/examples/stickiness/

**Comment by wangchengming666** [comment]
I'll fix it
