### ISSUE TITLE
Nacos 注册中心的增加Maven依赖

### ISSUE THREAD

**Issue by HeyChiang** [apache/dubbo-website#1069]
注册中心不同的nacos版本该如何引入对应dubbo的版本？ 另外apache的案例为什么引用的 com.aibaba的jar包?

感觉文档滞后很严重；
https://dubbo.apache.org/zh/docs/v2.7/user/references/registry/nacos/

**Comment by fanla2021** [comment]
> 注册中心不同的nacos版本该如何引入对应dubbo的版本？ 另外apache的案例为什么引用的 com.aibaba的jar包?
> 
> 感觉文档滞后很严重； https://dubbo.apache.org/zh/docs/v2.7/user/references/registry/nacos/

您好，新版本马上发出来，针对不同版本链接地址也不一样，docs/V2.7后面还会有V3.0这类的。
