### ISSUE TITLE
负载均衡 的优先级问题

### ISSUE THREAD

**Issue by HeyChiang** [apache/dubbo-website#1070]
服务端服务级别
客户端服务级别
服务端方法级别
客户端方法级别

如果他们都配置了负载均衡，优先级是下面从左到右来算吗？ 左边的优先级最高。

 服务端方法级别 > 服务端服务级别 > 客户端方法级别 > 客户端服务级别

**Comment by mfordjody** [comment]
客户端方法级别 -> 服务端服务级别 -> 服务端方法级别 -> 服务端服务级别，应该客户端方法最优先，服务端服务最后使用
