### ISSUE TITLE
where should I add description when I add a new feature to dubbo?

### ISSUE THREAD

**Issue by dragon-zhang** [apache/dubbo-website#1084]

**Comment by dragon-zhang** [comment]
@AlbumenJ @chickenlj Hi, for https://github.com/apache/dubbo/pull/10021, how can I add description?

**Comment by dragon-zhang** [comment]
https://dubbo.apache.org/en/docs/contribution-guidelines/contributor/new-contributor-guide_dev/ didn't mention this.

**Comment by AlbumenJ** [comment]
You can submit a docs in https://github.com/apache/dubbo-website/tree/master/content/zh/docs3-building/java-sdk/advanced-features-and-usage/performance . For content structure, you can refer to other documents.
