### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by hoset** [apache/dubbo-website#1089]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
https://dubbo.apache.org/ 目前无法访问，已经有3天了

**Comment by CrazyHZM** [comment]
@hoset 是指哪块内容无法访问？

**Comment by AlbumenJ** [comment]
https://dubbo.apache.org/ 目前是通过 fastly 分发的，由于商标和备案等原因无法在境内部署，最近的节点在hk和jp
