### ISSUE TITLE
服务流量管理

### ISSUE THREAD

**Issue by tmsnan** [apache/dubbo-website#1177]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/12018633/176853823-7a0d3012-7e21-457f-8a9f-43e98a33636a.png">
文档错误

**Comment by AlbumenJ** [comment]
可以提个 PR 修复下

**Comment by mfordjody** [comment]
之前修复过了 https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/routing/
