### ISSUE TITLE
服务调用扩展点

### ISSUE THREAD

**Issue by yeer0222** [apache/dubbo-website#1303]
如果需要在 Consumer 侧生效 Filter 或 ClusterFilter，需要增加 @Activate 注解，并且需要指定 group 的值为 provider。

应改为：

如果需要在 Provider 侧生效 Filter 或 ClusterFilter，需要增加 @Activate 注解，并且需要指定 group 的值为 provider。

**Comment by AlbumenJ** [comment]
可以提个PR修改下
