### ISSUE TITLE
文字表述错误

### ISSUE THREAD

**Issue by tianyuxingxuan** [apache/dubbo-website#1357]
调用链路传递隐式参数文档中：“A 调 B，B 再调 C，则 B 机器上，在 B 调 C 之前，RpcContext 记录的是 A 调 B 的信息，在 B 调 C 之后，RpcContext 记录的是 B 调 C 的信息”，RpcContext记录的应该是A和B的信息，如果是同步调用的话，这里应该表述B调用C是同步还是异步方式。

**Comment by AlbumenJ** [comment]
提个PR修复下
