### ISSUE TITLE
应用级服务发现 - 文档的编排有很大的问题，整体感觉很混乱

### ISSUE THREAD

**Issue by xishian** [apache/dubbo-website#1367]
一个新的feature，应该先介绍一下有什么用吧，解决了哪些原有的问题，适用于哪些场景，然后才是如何实施吧，最后跟一个FAQ

**Comment by AlbumenJ** [comment]
看的是哪一篇文档呢，能不能贴一下链接。

https://dubbo.apache.org/zh/docs3-v2/java-sdk/concepts-and-architecture/service-discovery/
https://dubbo.apache.org/zh/docs3-v2/java-sdk/upgrades-and-compatibility/service-discovery/service-discovery-samples/
https://dubbo.apache.org/zh/docs3-v2/java-sdk/upgrades-and-compatibility/service-discovery/migration-service-discovery/
https://dubbo.apache.org/zh/docs3-v2/java-sdk/upgrades-and-compatibility/service-discovery/service-discovery-rule/
