### ISSUE TITLE
dubbo2.7.13 集成sleuth brave-instrumentation-dubbo-rpc报错

### ISSUE THREAD

**Issue by liuzhimin1996** [apache/dubbo-website#1424]
我正在从feign更换为dubbo 但是sleuth就需要集成brave-instrumentation-dubbo-rpc才能正常传递tracId等信息
当消费端集成brave-instrumentation-dubbo-rpc 启动时会报
org.apache.dubbo.rpc.RpcException: Failed to invoke the method getServiceRestMetadata in the service org.apache.dubbo.rpc.service.GenericService. Tried 3 times of the providers [xx.xx.xx.xx:20880] (1/1) from the registry localhost:9090 on the consumer xx.xx.xx.xx using the dubbo version 2.7.13. Last error is: com.alibaba.dubbo.rpc.RpcContext.setFuture(Ljava/util/concurrent/Future;)V
 然后当rpc调用时
 org.apache.dubbo.rpc.RpcException: Failed to invoke the method loadPlayerByUsername in the service com.xxx.service.PlayerService. Tried 3 times of the providers [xx.xx.xx.xx:20880] (1/1) from the registry dev.sx.net:8848 on the consumer xx.xx.xx.xx using the dubbo version 2.7.13. Last error is: com.alibaba.dubbo.rpc.RpcContext.setFuture(Ljava/util/concurrent/Future;)V
如果不集成brave-instrumentation-dubbo-rpc  sleuth就会失效 但是启动时 以及rpc调用时不会报错

**Comment by AlbumenJ** [comment]
这个是 brave-instrumentation-dubbo-rpc 不支持高版本 Dubbo 的 API 导致的，需要 brave-instrumentation-dubbo-rpc 提供新版本的支持 
Related issue: https://github.com/openzipkin/brave/issues/947
