### ISSUE TITLE
代码架构图中,ExchangeServer ，多了一个字母 e

### ISSUE THREAD

**Issue by fengdh23** [apache/dubbo-website#1550]
![image](https://user-images.githubusercontent.com/4252100/194747487-05d5fdf6-69ae-4e37-b9af-fb2a7b800a1e.png)
ExchangeSerever should be  ExchangeServer .

**Comment by agmtopy** [comment]
你看的真的好仔细啊

**Comment by baerwang** [comment]
https://github.com/apache/dubbo-website/issues/698

**Comment by baerwang** [comment]
https://github.com/apache/dubbo-website/issues/605
