### ISSUE TITLE
blogs plan

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo-website#172]
计划在官网博客按照以下的目录发表系列博客，内容务求深入浅出，适合新手入门，对 Dubbo 能有一个全面的了解。以后考虑以博客的集成集结成书，所以写的时候请按写书的标准要求自己。标准就是 manning 出版社的 in action 系列。

* 博客文章请以 markdown 的格式放在 `blog/zh-cn` 下
* 目录请修改 `site_config/blog.js`
* 然后按照 `README.md` 来构建，本地先确认效果

> 提交 pull reuqest，确认效果后请清理本地文件，只接受 markdown 博客本体以及 blog.js 目录的修改

## 目录

> 目前拟定的目录，欢迎留言给出建议和意见，更欢迎进来一起贡献

####  1. RPC与服务框架
1. RPC简介  
2. RPC与服务化的关系
3. 注册中心，配置中心， 服务发现概念的介绍

#### 2. [第一个Dubbo应用](http://dubbo.apache.org/zh-cn/blog/dubbo-101.html)
1. 纯API编程
#### 3. Dubbo核心设计介绍
1. 配置
2. [数据总线 URL](http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-url.html) (DONE @lexburner)
3. [扩展机制](http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-spi.html) (DONE @vangoleo)
  1. [源码分析](http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-spi-2.html) (DONE @vangoleo)
4. 领域模型
5. 调用执行链 (@qinliujie )
6. [第一个 Filter](http://dubbo.apache.org/zh-cn/blog/first-dubbo-filter.html) (DONE @nzomkxia) 

### 二、Dubbo基本用法
> 用spring xml方式，如果能用纯API方式，建议优先使用
####   1. [Dubbo Provider](http://dubbo.apache.org/zh-cn/blog/dubbo-basic-usage-dubbo-provider-configuration.html) (DONE @cvictory)
1. ~~Provider配置详解~~
2. ~~Provider接口，实现~~  
####   2. [Dubbo Consumer](http://dubbo.apache.org/zh-cn/blog/dubbo-basic-usage-dubbo-consumer-configuration.html) (DONE @cvictory)
1. ~~Consumer配置详解~~
2. ~~Consumer实现~~
####   3. [Zookeeper](http://dubbo.apache.org/zh-cn/blog/dubbo-zk.html)  (DONE @beiwei30)
1. ~~可以简单回顾一下第一章介绍的注册中心，注册中心在RPC中的作用~~
2. ~~Zookeeper的配置 启动~~
####   4. [QOS](http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-qos.html) (DONE @ralf0131)
1. ~~通过QoS对服务进行动态控制~~
####   5. ~~使用方式~~
> 此部分在的Dubbo Provider中有介绍，不再单独介绍了
1. ~~基于xml~~
2. ~~基于api配置~~
3. ~~基于注解配置~~
####   6. [调用方式](http://dubbo.apache.org/zh-cn/blog/dubbo-invoke.html) (DONE @diecui1202)
1. ~~异步调用~~
2. ~~参数回调~~
3. ~~事件通知~~
4. [泛化调用](http://dubbo.apache.org/zh-cn/blog/dubbo-generic-invoke.html) (DONE @diecui1202)
####   1. 本地
1. 本地调用
2. 本地存根
3. 本地伪装(服务降级)
####    2. 信息传递
1. [上下文信息](http://dubbo.apache.org/zh-cn/blog/dubbo-context-information.html) (DONE @guohao)
2. 隐式参数 (@guohao )
####    3. 集群
1. [负载均衡策略](http://dubbo.apache.org/zh-cn/blog/dubbo-loadbalance.html) (DONE @vangoleo)
2. [集群容错](http://dubbo.apache.org/zh-cn/blog/dubbo-cluster-error-handling.html) (DONE @ralf0131 )
####    4. [服务分组和版本](http://dubbo.apache.org/zh-cn/blog/service-and-version.html) (DONE @nzomkxia )
1. ~~服务分组~~ 
2. ~~多版本~~
3. ~~分组聚合~~
####    5. [测试验证](http://dubbo.apache.org/zh-cn/blog/test-verification.html) (DONE @nzomkxia )
1. ~~只订阅~~
2. ~~指定ip调用~~
3. ~~回声测试~~
####    6. 运维相关
1. 优雅停机 (@guohao )
2. 服务日志 
### 四、Dubbo服务运维
> 只强调控制台中跟服务运维，监控相关的部分，目的是介绍服务运维，不是控制台
####   1. 控制台
1. 服务查询
2. 路由规则配置
3. 其他规则配置？
4. mock server？
5. api管理？
####   2. monitor  
1. 服务监控？
2. 指标配置？
### 五、最佳实践 
> 有场景，可以讲故事，跟扩展的特性结合起来
####  6. 熔断
1. [集成hystrix](http://dubbo.apache.org/zh-cn/blog/dubbo-integrate-with-hystrix.html) (DONE @hengyunabc )
2. [集成sentinel](http://dubbo.apache.org/zh-cn/blog/sentinel-introduction-for-dubbo.html) (DONE @sczyh30 )
3. 集成resilience4j
####  8. 与 spring boot 如何混用
> 要看前面是基于spring还是spring boot
1. [Dubbo Spring Boot应用启停源码分析](http://dubbo.apache.org/zh-cn/blog/spring-boot-dubbo-start-stop-analysis.html) (DONE @ralf0131 )
2. ~~优雅关闭spring-boot+Dubbo应用~~
####  9. 分布式跟踪
1. [集成Zipkin](http://dubbo.apache.org/zh-cn/blog/use-zipkin-in-dubbo.html) (DONE @beiwei30 )
2. [集成Skywalking](http://dubbo.apache.org/zh-cn/blog/tracing-with-skywalking.html) (DONE 张鑫)
3. [集成pinpoint](http://dubbo.apache.org/zh-cn/blog/pinpoint.html) (DONE @majinkai )
#### 6. API

**Comment by manzhizhen** [comment]
最佳实践 //有场景，可以讲故事，跟扩展的特性结合起来
  1  分组
  2  容灾
  3  升级
  4  线程
  5  调优
  6  熔断
  1  ~~集成hystrix~~

来来来一起共建！！！

**Comment by chickenlj** [comment]
-- 本地伪装(服务降级)|

我来写这个文档

**Comment by hengyunabc** [comment]
* QOS
* 通过QoS对服务进行动态控制

我来写下这个

**Comment by nzomkxia** [comment]
Dubbo服务运维

**Comment by beiwei30** [comment]
REST

**Comment by guohao** [comment]
上下文信息
隐式参数
优雅停机

**Comment by cvictory** [comment]
> 最佳实践 //有场景，可以讲故事，跟扩展的特性结合起来
> 1 分组
> 2 容灾
> 3 升级
> 4 线程
> 5 调优
> 6 熔断
> 1 集成hystrix
> 
> 来来来一起共建！！！

这几个你有写吗？ 不写的话，我就要开始挑了

**Comment by Authorlove** [comment]
附录：
4. 协议

我来写下这个

**Comment by qinliujie** [comment]
3.6 调用执行链 我来认领这篇

**Comment by uglycow** [comment]
5.0 服务测试
只订阅
指定ip调用
回声测试

**Comment by caojiele** [comment]
以这个目录为提纲，然后看你们写了哪些，我挑剩下的。

**Comment by Authorlove** [comment]
认领
6. 熔断
    3.集成resilience4j

**Comment by beiwei30** [comment]
#### 4. [服务分组和版本](http://dubbo.apache.org/zh-cn/blog/service-and-version.html)
1. 服务分组
2. 多版本
3. 分组聚合

**Comment by beiwei30** [comment]
#### 本地
1. 本地调用
2. 本地存根

**Comment by lkxiaolou** [comment]
`site_config/blog.js` 这个文件现在没了？
