### ISSUE TITLE
泛化调用（客户端泛化）

### ISSUE THREAD

**Issue by fallendx** [apache/dubbo-website#1755]
泛化调用方使用的demo
`referenceConfig.setApplication(applicationConfig);` 
方法已经废弃

**Comment by yuluo-yx** [comment]
Do you have enough evidence that this method is outdated?

**Comment by fallendx** [comment]
> 

org.apache.dubbo.config.AbstractInterfaceConfig#setApplication

`@Deprecated
    public void setApplication(ApplicationConfig application) {
        this.application = application;
        if (application != null && getContext() != null) {
            ConfigManager configManager = ApplicationModel.getConfigManager();
            configManager.getApplication().orElseGet(() -> {
                configManager.setApplication(application);
                return application;
            });
        }
    }`

**Comment by AlbumenJ** [comment]
> 泛化调用方使用的demo `referenceConfig.setApplication(applicationConfig);` 方法已经废弃

这个需要都重构成基于 DubboBootstrap 的使用方式
