### ISSUE TITLE
Add New PMC guide

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo-website#187]
Add new pmc guide to http://dubbo.apache.org/en-us/docs/developers/developers_dev.html

**Comment by caojiele** [comment]
> Add new pmc guide to http://dubbo.apache.org/en-us/docs/developers/developers_dev.html

@ralf0131 If there are any contribution can be added?

**Comment by ralf0131** [comment]
I think the New PMC guide should be written by someone who is at least a PPMC member, I am planning to work on this.

I'd appreciate your enthusiasm on this, I think it is better to contribute to other issues first :)

**Comment by caojiele** [comment]
> I think the New PMC guide should be written by someone who is at least a PPMC member, I am planning to work on this.
> 
> I'd appreciate your enthusiasm on this, I think it is better to contribute to other issues first :)

OK，sir.
