### ISSUE TITLE
Dead links under the community page.

### ISSUE THREAD

**Issue by code4wt** [apache/dubbo-website#198]
There are three dead links under the community page, as follow:

http://dubbo.apache.org/zh-cn/blog/dubbo-meetup-beijing-may-12th-2018.html
http://dubbo.apache.org/zh-cn/blog/apachecon-na-2018.html
http://dubbo.apache.org/zh-cn/blog/qcon-beijing-2018.html

![](http://blog-pictures.oss-cn-shanghai.aliyuncs.com/tmp/image.png)

**Comment by ralf0131** [comment]
Hi, I can confirm this issue, because these 3 articles does not have Chinese version, would you help to translate them into Chinese?

**Comment by ralf0131** [comment]
To help on this issue (as an example), copy `blog/en-us/dubbo-meetup-beijing-may-12th-2018.md`  to `blog/zh-cn/dubbo-meetup-beijing-may-12th-2018.md`  and replace the content with Chinese.
