### ISSUE TITLE
3 - Dubbo x Spring Boot 开发微服务应用

### ISSUE THREAD

**Issue by ArtanisL** [apache/dubbo-website#2291]
位置：3. 添加 Maven 依赖->编辑 ./dubbo-spring-boot-consumer/pom.xml 和 ./dubbo-spring-boot-provider/pom.xml 这两文件，都添加下列配置。

问题：配置项 interface 的依赖有问题，填写的是 dubbo-samples 工程中的artifactId
预期：实际上应该填写 dubbo-spring-boot-demo-interface

**Comment by AlbumenJ** [comment]
Please submit a PR to fix it.

**Comment by ArthurCats** [comment]
我也碰到这个问题了。
