### ISSUE TITLE
IDL defines cross-language services

### ISSUE THREAD

**Issue by hqqeee** [apache/dubbo-website#2462]
Paragraph 7 includes a code snippet that uses the configuration `.registry(new RegistryConfig("multicast://127.0.0.1:2181"))`.
The multicast addresses are in the range 224.0. 0.0 through 239.255. 255.255. So I believe it's a typo and should be zookeeper because in the client code snippet it uses:
`.registry(new RegistryConfig("zookeeper://127.0.0.1:2181"))`.
Additionally, it would be beneficial to include information about how to start the registration center in the tutorial.

**Comment by AlbumenJ** [comment]
Would you please submit a PR to fix it?
