### ISSUE TITLE
Apache APISIX

### ISSUE THREAD

**Issue by nuccch** [apache/dubbo-website#2463]
在实践demo验证的时候，创建HTTP路由这一步报错：
```shell
{"error_msg":"unknown plugin [dubbo-proxy]"}
```
我是通过 https://github.com/apache/apisix-docker.git (使用分支release/apisix-2.12.0，对应APISIX版本为2.11.0)以Docker方式启动的APISIX实例。

**Comment by AlbumenJ** [comment]
Would you please help create a issue in apache/apisix?
