### ISSUE TITLE
Spring Boot 快速开发 Dubbo 服务

### ISSUE THREAD

**Issue by AYiXi** [apache/dubbo-website#2574]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/28703786/234249146-0db4d46e-d713-4aec-8a51-85f80fb415a9.png">
按照示例一步一步运行, 直接报错, 什么玩意儿

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/234445467-c7b594ac-3b7b-4d8b-80f2-529c4ed92994.png)

这一步执行了嘛

**Comment by AYiXi** [comment]
> ![image](https://user-images.githubusercontent.com/9292748/234445467-c7b594ac-3b7b-4d8b-80f2-529c4ed92994.png)
> 
> 这一步执行了嘛

没有, 但是照着阿里云的一个文档执行的, 好像没有这个, 现在已经配置好了, 谢谢
