### ISSUE TITLE
[ci] Link failure

### ISSUE THREAD

**Issue by mfordjody** [apache/dubbo-website#2693]
![image](https://github.com/apache/dubbo-website/assets/91593982/9650e84f-dc04-46e5-8e9a-3e2957b9c5a4)

**Comment by mfordjody** [comment]
@AlbumenJ Maybe you can find a better way :)

**Comment by AlbumenJ** [comment]
We can add them into excluded list. The connection check is to check if we change some link but forgot to update them on website.
