### ISSUE TITLE
功能-流量管控-条件路由 文档

### ISSUE THREAD

**Issue by demo0816** [apache/dubbo-website#2697]
## Expected Behavior

[条件路由规则文档](https://cn.dubbo.apache.org/zh-cn/overview/core-features/traffic/condition-rule/ )  中，有个after单词重复了

The behaviour when the instance subset is empty after after routing. true means return no provider exception while false means ignore this rule.
--

==>

The behaviour when the instance subset is empty after routing. true means return no provider exception while false means ignore this rule.
--

**Comment by AlbumenJ** [comment]
Would you please submit a PR to fix?
