### ISSUE TITLE
文档底部的钉钉群二维码失效

### ISSUE THREAD

**Issue by aomsir** [apache/dubbo-website#2787]
## Describe the proposal
文档底部那个“Dubbo社区贡献者”钉钉群二维码失效，望更新。

**Comment by AlbumenJ** [comment]
是哪个文档呢

**Comment by aomsir** [comment]
https://cn.dubbo.apache.org/zh-cn/
<img width="1200" alt="image" src="https://github.com/apache/dubbo-website/assets/60360782/18e568f4-5dfb-436d-99bc-eb82545358d2">
