### ISSUE TITLE
[WebSite]: Skywalking OAP

### ISSUE THREAD

**Issue by yuluo-yx** [apache/dubbo-website#2818]
Link: https://cn.dubbo.apache.org/zh-cn/overview/tasks/observability/tracing/skywalking/#4-%E5%90%AF-skywalking-oap

Maybe :启动"

![image](https://github.com/apache/dubbo-website/assets/77964041/a34a87d3-ab23-48b6-8255-f57d0d7382ba)

**Comment by AlbumenJ** [comment]
Would u pls submit a PR to fix it?

**Comment by yuluo-yx** [comment]
> Would u pls submit a PR to fix it?

yep, pls assign to me.

**Comment by yuluo-yx** [comment]
Now complete, closed
