### ISSUE TITLE
"reporting security issues" section has disappeared from the docs

### ISSUE THREAD

**Issue by raboof** [apache/dubbo-website#2916]
## Expected Behavior

There should be a page explaining how to report security issues in Dubbo

## Actual Behavior

This page seems to have disappeared in #2878 : it was in `content/en/blog/security-notices/security.md` but there does not seem to be a replacement for this page.

**Comment by AlbumenJ** [comment]
In https://dubbo.apache.org/en/overview/notices/

**Comment by AlbumenJ** [comment]
> I don't see a "Reporting security issues" section there? (like in https://github.com/apache/dubbo-website/pull/2878/files#diff-2c228ef5dc9beda04cf108e1414abfb009373de833121dcbcf4a139aa87eec7cL10)

I will add this section later.

**Comment by raboof** [comment]
Looks great, thanks!
