### ISSUE TITLE
开发服务

### ISSUE THREAD

**Issue by yskgood** [apache/dubbo-website#2926]
示例代码中服务的分组和和版本和Provider不一致
GenericService genericService = buildGenericService("org.apache.dubbo.samples.develop.DevelopService","group2","2.0");
![image](https://github.com/apache/dubbo-website/assets/3283271/3d6ca274-7896-45b2-ba48-75b95477f8d2)

**Comment by yskgood** [comment]
文档地址：https://cn.dubbo.apache.org/zh-cn/overview/tasks/develop/generic/

**Comment by AlbumenJ** [comment]
Can you please submit a PR to fix?
