### ISSUE TITLE
泛化调用 | provider接口是一个泛型类（class A (T extends B)), 泛化调用报错

### ISSUE THREAD

**Issue by iamJunPan** [apache/dubbo-website#2943]
java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: java.lang.RuntimeException java.lang.RuntimeException at org.apache.dubbo.common.utils.PojoUtils.newInstance(PojoUtils.java:555) at org.apache.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:452) at org.apache.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:467) at org.apache.dubbo.common.utils.PojoUtils.realize(PojoUtils.java:209) at org.apache.dubbo.common.utils.PojoUtils.realize(PojoUtils.java:97) at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:86) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) at com.navercorp.pinpoint.plugin.reactive.auth.dubbo.apache.AuthProviderFilter.invoke(AuthProviderFilter.java:34) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:145) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175) at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Caused by: java.lang.InstantiationException at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source) at java.lang.reflect.Constructor.newInstance(Unknown Source) at org.apache.dubbo.common.utils.PojoUtils.newInstance(PojoUtils.java:553)

**Comment by AlbumenJ** [comment]
Please submit the issue to apache/dubbo
