### ISSUE TITLE
dubbo3.0.8对java.util.List序列化失败

### ISSUE THREAD

**Issue by hobartaoxiang** [apache/dubbo-website#2945]
![image](https://github.com/apache/dubbo-website/assets/162080501/24ba7e9a-edc7-493d-9cd8-b8653f3bf6e0)

dubbo版本： 3.0.8
jdk版本: 17

我换了fastjson、kryo序列化方案都是序列化失败的。 是不支持对java.util.List的序列化吗？

**Comment by AlbumenJ** [comment]
Please submit a discussion in https://github.com/apache/dubbo
