### ISSUE TITLE
nacos dns-f无法正常解析nacos server里面的服务

### ISSUE THREAD

**Issue by bingochenke** [apache/dubbo-website#2981]
![image](https://github.com/apache/dubbo-website/assets/16933724/7ff48f46-913a-4254-a34c-00e1cbc733a8)
![image](https://github.com/apache/dubbo-website/assets/16933724/db11fbd7-b8cd-405e-8428-2886a472e06c)
![image](https://github.com/apache/dubbo-website/assets/16933724/78fe8ed2-6366-4a51-a089-ac77ad199bf8)

nacos服务正常，配置检查也没问题，网络也没问题，dig之后还是无法找到该服务的ip,麻烦看下是什么原因

**Comment by bingochenke** [comment]
![image](https://github.com/apache/dubbo-website/assets/16933724/9c651aa9-daac-4cc9-9913-f26107471f42)
配置是这个，一直无法正常获取到服务，是什么环境原因导致的吗

**Comment by AlbumenJ** [comment]
Please submit issue to alibaba/nacos
