### ISSUE TITLE
无法修改Dubbo主机绑定

### ISSUE THREAD

**Issue by RicKey3-C** [apache/dubbo-website#3035]
![image](https://github.com/user-attachments/assets/a0807b07-f411-4e21-9f90-5ef68d2151f0)
我想用虚拟机docker的nacos作为注册中心，但是修改了dubbo.protocol.host之后，怎么还是试图用本机地址去注册

**Comment by AlbumenJ** [comment]
https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/config/properties/#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F
