### ISSUE TITLE
Spring Boot Starter 配置 `protocol` 是否存在错误

### ISSUE THREAD

**Issue by HaceraI** [apache/dubbo-website#3044]
根据文档进行配置后 [点击查看文档](https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/tasks/develop/springboot/#applicationyml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)，运行后提示：
java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name triple, no related exception was found, please check whether related SPI module is missing.
![image](https://github.com/user-attachments/assets/20a50bff-445c-4e03-90c0-28526b53296d)

是不是应该这样配置才是正确的：
```yml
dubbo:
  protocol:
    port: -1
    # triple  ---->  tri
    name: tri
```

还是说如果需要使用 Triple X 的话，还得再增加其他依赖呢？
```xml
<dependencies>
    <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-spring-boot-starter</artifactId>
    </dependency>
    <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-nacos-spring-boot-starter</artifactId>
    </dependency>
</dependencies>
```

Dubbo Version: 3.3.1
Java Version: 21

**Comment by AlbumenJ** [comment]
Use tri, not `triple`
