### ISSUE TITLE
创建基于Spring Boot的微服务应用

### ISSUE THREAD

**Issue by hellolcl** [apache/dubbo-website#3068]
![image](https://github.com/user-attachments/assets/592c45a8-bc87-4c26-8e64-a0a2c2292816)
最后两个词重复，应该为："同时可以看到消费端持续对提供端发起调用："

**Comment by finefuture** [comment]
Would you like to submit a pr fix it?

**Comment by hellolcl** [comment]
> Would you like to submit a pr fix it?
submit a PR：https://github.com/apache/dubbo-website/pull/3076. link check fail，how to fix it？
