### ISSUE TITLE
Extra styles in markdown

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo-website#320]
There is extra styles in https://github.com/apache/incubator-dubbo-website/blob/asf-site/docs/zh-cn/user/references/xml/dubbo-config-center.md

**Comment by caojiele** [comment]
Which extra styles？

**Comment by ralf0131** [comment]
@caojiele In the top, there is something like below, which is unnecessary:

<style> table { width: 100%; max-width: 65em; border: 1px solid #dedede; margin: 15px auto; border-collapse: collapse; empty-cells: show; } table th, table td { height: 35px; border: 1px solid #dedede; padding: 0 10px; } table th { font-weight: bold; text-align: center !important; background: rgba(158,188,226,0.2); white-space: nowrap; } table tbody tr:nth-child(2n) { background: rgba(158,188,226,0.12); } table td:nth-child(1) { white-space: nowrap; } table tr:hover { background: #efefef; } .table-area { overflow: auto; } </style> <script type="text/javascript"> [].slice.call(document.querySelectorAll('table')).forEach(function(el){ var wrapper = document.createElement('div'); wrapper.className = 'table-area'; el.parentNode.insertBefore(wrapper, el); el.parentNode.removeChild(el); wrapper.appendChild(el); }) </script>

**Comment by caojiele** [comment]
@ralf0131 Are all the articles in this directory are not these styles？

**Comment by ralf0131** [comment]
@caojiele  Ideally the styles should not go into markdown file.
