### ISSUE TITLE
‘ Here’ link in CHANGES.md is invalid

### ISSUE THREAD

**Issue by lixiaojiee** [apache/dubbo-website#346]
Does it have to be replaced with an upgrade guide link for the official website?
http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html

[#3732](https://github.com/apache/incubator-dubbo/issues/3732)

**Comment by caojiele** [comment]
So where are these guide links?

**Comment by lixiaojiee** [comment]
> So where are these guide links?

In-page jump

**Comment by caojiele** [comment]
> > So where are these guide links?
> 
> In-page jump

I know in-page jump, where is links? It is best to summed up the corresponding link.

**Comment by caojiele** [comment]
> > So where are these guide links?
> 
> In-page jump

文中的`Dubbo配置方式`和异步API`使用示例`有对应链接吗？

**Comment by lixiaojiee** [comment]
> > > So where are these guide links?
> > 
> > 
> > In-page jump
> 
> 文中的`Dubbo配置方式`和异步API`使用示例`有对应链接吗？

如下面截图中的包重命名，需要链接到该页下面的 “包名改造”
![image](https://user-images.githubusercontent.com/34837528/61938987-e1e76580-afc4-11e9-9e81-39f2975d99b5.png)

**Comment by caojiele** [comment]
> > > > So where are these guide links?
> > > 
> > > 
> > > In-page jump
> > 
> > 
> > 文中的`Dubbo配置方式`和异步API`使用示例`有对应链接吗？
> 
> 如下面截图中的包重命名，需要链接到该页下面的 “包名改造”
> ![image](https://user-images.githubusercontent.com/34837528/61938987-e1e76580-afc4-11e9-9e81-39f2975d99b5.png)

OK, I will try fix it:)
