### ISSUE TITLE
Blog & Docs translation plan

### ISSUE THREAD

**Issue by caojiele** [apache/dubbo-website#368]
The following articles need to be translated,
It's still a work in progress. I will continuously push to this issue.
Please comply with the Guide for adding new document.

## Table of contents
> Currently proposed contents, welcome message give Suggestions and contributions together.

#### **1. From Chinese to English**

| document          | translator                | status                       | 
| --------------- | ------------------- | ------------------- | 
|[rpc-introduction.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/rpc-introduction.md)|[TingSky](https://github.com/TingSky)||
| [dubbo-27-features.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-27-features.md)|||
|[build-new-docker-image-in-dockerhub.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/build-new-docker-image-in-dockerhub.md)|||
|[dubbo-admin.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-admin.md)|[zhenxianyimeng](https://github.com/zhenxianyimeng)||
|[dubbo-annotation-driven.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-annotation-driven.md)|[complone](https://github.com/complone)||
|[dubbo-basic-usage-dubbo-consumer-configuration.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-basic-usage-dubbo-consumer-configuration.md)|[complone](https://github.com/complone)||
|[dubbo-cluster-error-handling.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-cluster-error-handling.md)|||
|[dubbo-compatible.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-compatible.md)|||
|[dubbo-context-information.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-context-information.md)||
|[dubbo-contribute-to-opensource.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-contribute-to-opensource.md)|||
|[dubbo-copywriting-style.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-copywriting-style.md)|||
|[dubbo-echo-test.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-echo-test.md)|||
|[dubbo-externalized-configuration.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-externalized-configuration.md)|||
|[dubbo-gracefully-shutdown.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-gracefully-shutdown.md)|[Moriadry](https://github.com/Moriadry)||
|[dubbo-heartbeat-design.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-heartbeat-design.md)|||
|[dubbo-integrate-with-hystrix.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-integrate-with-hystrix.md)|||
|[dubbo-local-call.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-local-call.md)|||
|[dubbo-meet-arthas.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-meet-arthas.md)|[Moriadry](https://github.com/Moriadry)||
|[dubbo-mesh-in-thinking.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-mesh-in-thinking.md)|||
|[duboo-mesh-service-mesh-exploring.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-mesh-service-mesh-exploring.md)|||
|[dubbo-protocol.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-protocol.md)|[catxu](https://github.com/catxu)|**done**|
|[dubbo-registry-nacos-integration.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-registry-nacos-integration.md)|[githublaohu](https://github.com/githublaohu)||
|[dubbo-rest.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-rest.md)|||
|[dubbo-stub-mock.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-stub-mock.md)|||
|[dubboAsync_client.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubboAsync_client.md)|[Kyle](https://github.com/sofkyle)|**done**|
|[dubboAsync_server.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubboAsync_server.md)|[Kyle](https://github.com/sofkyle)|**done**|
|[first-dubbo-filter.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/first-dubbo-filter.md)|[zhenxianyimeng](https://github.com/zhenxianyimeng)|**done**|
|[how-to-involve-dubbo-communtity.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/how-to-involve-dubbo-community.md)||
|[introduction-to-dubbo-url.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/introduction-to-dubbo-url.md)|||
|[meet-dubbo.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/meet-dubbo.md)|[Moriadry](https://github.com/Moriadry)||
|[service-and-version.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/service-and-version.md)|||
|[service-test.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/service-test.md)|[maoyanting](https://github.com/maoyanting)|**done**|
|[test-verification.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/test-verification.md)|||
|[use-zipkin-in-dubbo.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/use-zipkin-in-dubbo.md)|||

####  **2. From English to Chinese**

| document          | translator                | status                       | 
| --------------- | ------------------- | ------------------- | 
| [qsoc-2018.md](https://github.com/apache/dubbo-website/blob/master/blog/en-us/gsoc-2018.md)|[caojiele](https://github.com/caojiele)| **done** |

#### **1. From Chinese to English**

| document          | translator                | status                       | 
| --------------- | ------------------- | ------------------- | 
|[config-center.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/dev/impls/config-center.md)|[mzorro](https://github.com/mzorro)|**done**|
|[configuration-load-process.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/configuration/configuration-load-process.md)|[mzorro](https://github.com/mzorro)|**done**|
|[dubbo-config-center.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/references/xml/dubbo-config-center.md)|[mzorro](https://github.com/mzorro)|**done**|
|[async-call-deprecated.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/demos/async-call-deprecated.md)|[complone](https://github.com/complone)|**done**|
|[async-execute-on-provider.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/demos/async-execute-on-provider.md)|[farliu](https://github.com/farliu)|**done**|
|[config-rule-deprecated.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/demos/config-rule-deprecated.md)|[csxiaoshang](https://github.com/csxiaoshang)|**done**|
|[routing-rule-deprecated.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/demos/routing-rule-deprecated.md)|||
|[set-host.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/demos/set-host.md)|[Moriadry](https://github.com/Moriadry)|||
|[simplify-registry-data.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/demos/simplify-registry-data.md)|||
|[adaptive-extension.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/adaptive-extension.md)|||
|[cluster.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/cluster.md)|||
|[directory.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/directory.md)|||
|[dubbo-spi.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/dubbo-spi.md)|||
|[export-service.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/export-service.md)|||
|[loadbalance.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/loadbalance.md)|||
|[refer-service.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/refer-service.md)|||
|[router.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/router.md)|||
|[service-invoking-process.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/source_code_guide/service-invoking-process.md)|||
|[introduction.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/references/metadata/introduction.md)|[Kyle](https://github.com/sofkyle)|**done**||
|[version-270.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/user/versions/version-270.md)|||

####  **2. From English to Chinese**

| document          | translator                | status                       | 
| --------------- | ------------------- | ------------------- | 
|[properties.md](https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/configuration/properties.md)|[kowasaretaneko17](https://github.com/kowasaretaneko17)|**done**||
|[become-a-committer_dev.md](https://github.com/apache/dubbo-website/blob/master/docs/en-us/developers/contributor-guide/become-a-committer_dev.md)|[farliu](https://github.com/farliu)|**done**||
|[reporting-security-issues_dev.md](https://github.com/apache/dubbo-website/blob/master/docs/zh-cn/developers/contributor-guide/reporting-security-issues_dev.md)|[withthewind](https://github.com/lzf971107)|**done**||

**Comment by complone** [comment]
Can I claim it?

**Comment by caojiele** [comment]
> Can I claim it?

Sure, please pay attention to submit items.

**Comment by lovepoem** [comment]
I think the form of your translation project can be more convenient for translators.

e.g.  

**1 .From Chinese to   Chinese**

document address | translator | status
-- | -- | -- |
[rest.md](https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/references/protocol/rest.md)|  
  ||

**2 . From English to Chinese  **

document address | translator | status
-- | -- | -- |
[rest.md](https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/references/protocol/rest.md)|  
  ||

**Comment by qzzsunly** [comment]
认领   [versions](https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/configuration/properties.md)

**Comment by kowasaretaneko17** [comment]
认领  
properties.md

**Comment by caojiele** [comment]
> 认领
> https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/configuration/properties.md

👍

**Comment by farliu** [comment]
认领：generic-service.md

**Comment by maoyanting** [comment]
认领 [service-test.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/service-test.md)
do my best ✊

**Comment by mzorro** [comment]
Claim docs: 
config-center.md
configuration-load-process.md
dubbo-config-center.md

**Comment by farliu** [comment]
认领：async-execute-on-provider.md

**Comment by farliu** [comment]
认领：
async-execute-on-provider.md
become-a-committer_dev.md

**Comment by Moriadry** [comment]
claim:

Blog: 
dubbo-gracefully-shutdown.md
dubbo-meet-arthas.md
meet-dubbo.md

Doc:
set-host.md

**Comment by zhenxianyimeng** [comment]
claim:
blog:
first-dubbo-filter.md

let me try one

**Comment by sofkyle** [comment]
CLAIM:

BLOG:
dubboAsync_client.md		
dubboAsync_server.md

DOC:
metadata/introduction.md

**Comment by kowasaretaneko17** [comment]
> 认领
> https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/configuration/properties.md

![image](https://user-images.githubusercontent.com/28587974/63738915-0e411b00-c8be-11e9-8d1c-08e9d8b981b0.png)

**Comment by caojiele** [comment]
> > 认领
> > https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/configuration/properties.md
> 
> ![image](https://user-images.githubusercontent.com/28587974/63738915-0e411b00-c8be-11e9-8d1c-08e9d8b981b0.png)

Good job! 👍 Someone to review it.  Can you claim other tasks?

**Comment by kowasaretaneko17** [comment]
> > > 认领
> > > https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/configuration/properties.md
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/28587974/63738915-0e411b00-c8be-11e9-8d1c-08e9d8b981b0.png)
> 
> Good job! 👍 Someone to review it. Can you claim other tasks?

I thought I only can do something like translating them from English to Chinese 。But ，reversly，I may make a real mess-up of those。I also hope to join in perfecting the project as a coder in future。（www

**Comment by catxu** [comment]
Claim:
Blog - From Chinese to English:
dubbo-protocol.md

**Comment by TingSky** [comment]
Claim:
Blog - From Chinese to English:
rpc-introduction.md

**Comment by zhenxianyimeng** [comment]
claim:
blog:
[dubbo-admin.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-admin.md)

**Comment by githublaohu** [comment]
认领
[dubbo-registry-nacos-integration.md](https://github.com/apache/dubbo-website/blob/master/blog/zh-cn/dubbo-registry-nacos-integration.md)

**Comment by csxiaoshang** [comment]
claim:
DOC:
config-rule-deprecated.md
