### ISSUE TITLE
Wrong description about dubbo:registry's extra-keys

### ISSUE THREAD

**Issue by kexianjun** [apache/dubbo-website#371]
the dubbo:registry's extra-keys config [dubbo:registry](http://dubbo.incubator.apache.org/zh-cn/docs/user/references/xml/dubbo-registry.html) description about it's Compatibility is wrong, which is not from version 2.0.5, and the extra-keys's description is missing from the English version.

**Comment by lixiaojiee** [comment]
Would you mind sending a pr to fix it?
