### ISSUE TITLE
Admin guide->service test has nothing

### ISSUE THREAD

**Issue by OpenDoing** [apache/dubbo-website#379]
Web tell me a blog but this blog is not exist.

**Comment by DLive** [comment]
It only has Chinese pages. Many blogs have not been translated yet.

**Comment by DLive** [comment]
The target url is http://dubbo.apache.org/zh-cn/blog/service-test.html. 
I will create a PR for it.

**Comment by htynkn** [comment]
New htmls gerenated. This should fixed
