### ISSUE TITLE
本地伪装 是否是文字错误【 mock="force:return fake】

### ISSUE THREAD

**Issue by github-bruce2015** [apache/dubbo-website#405]
<dubbo:reference interface="com.foo.BarService" mock="force:return fake" />

fake ---> false

**Comment by lixiaojiee** [comment]
在该示例下是没问题的，如果找不到empty、null、true和false，dubbo会判断调用方法的返回值是否是String，如果是String会将return值转换成String。除此之外，return还支持json格式数据和任何对象返回，只要return值能正常转化成方法返回值对应类型的对象即可。这个示例中只有一个sayHello方法，其返回值正好是String，故最终将fake转换成String 类型。

**Comment by lixiaojiee** [comment]
This issue has been resolved, now I will close it.

**Comment by github-bruce2015** [comment]
意思是只要这个配置在方法级别指定，return的值只要能转化为方法的返回值类型即可，服务消费端根据这个值来执行相应代码。
那这种配置放在服务接口级别是否合适呢？ 比如这个接口下的方法的返回值类型不一致
