### ISSUE TITLE
【升级与可能的兼容性问题总结】下文字位置错位

### ISSUE THREAD

**Issue by github-bruce2015** [apache/dubbo-website#408]
![微信截图_20190618165940](https://user-images.githubusercontent.com/19780775/59668173-97671200-91ea-11e9-8299-b833b0910750.png)

**Comment by lixiaojiee** [comment]
Would you mind sending a pr to fix it?

**Comment by htynkn** [comment]
Fixed via https://github.com/apache/dubbo-website/commit/2db949facde1bb4bd4b9d48fb67aad8f751d4f24#diff-c6c34e2333ef29724c806d5e436a7eefR252
