### ISSUE TITLE
路由规则文档一处笔误

### ISSUE THREAD

**Issue by thisiswanghy** [apache/dubbo-website#427]
其中降级约定第一点描述的:
如果要该表这种默认行为，即找不到匹配tag1的provider返回异常
应该是
如果要改变这种默认行为，即找不到匹配tag1的provider返回异常

该表->改变

**Comment by thisiswanghy** [comment]
地址:http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html

**Comment by lixiaojiee** [comment]
Thanks for your report, would you mind sending a pr to fix it?
