### ISSUE TITLE
user/references/protocol/rest.md  should be translated to English

### ISSUE THREAD

**Issue by lovepoem** [apache/dubbo-website#447]
http://dubbo.apache.org/en-us/docs/user/references/protocol/rest.html 

should be translated to English

Source doc is here ：
https://github.com/apache/dubbo-website/blob/master/docs/en-us/user/references/protocol/rest.md

**Comment by caojiele** [comment]
#368 Hi, questions about translation unified handling [here](https://github.com/apache/dubbo-website/issues/368).

**Comment by lovepoem** [comment]
OK
