### ISSUE TITLE
Error reporting while building the project: Cannot find module 'css-animation/lib/Event'

### ISSUE THREAD

**Issue by maoyanting** [apache/dubbo-website#462]
### Steps to reproduce

1. Run `npm install docsite -g` to install the dev tool.
2. Run `npm i in` the root directory to install the dependencies.
3. Run `docsite start` in the root directory to start a local server, you will see the website in 'http://127.0.0.1:8080'.

### What is expected?
Build should be done without any error

### What is actually happening?
Getting below error
```
(node:1835) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'css-animation/lib/Event'
```

I search for this error and find it may cause by `Antd`.
Antd' issue about this :[Antd Webpack build failing (Can't resolve 'css-animation/es/Event') ](https://github.com/ant-design/ant-design/issues/17928)

I follow the solution above and it make success, the blog can be displayed correctly.

I am not sure if it only happens to me because it's a question about a mouth ago.
If it's a question happen to everyone, please fix it; otherwise, close my issue.

**Comment by lovepoem** [comment]
`node -v` ,  please make sure the version of  your node.js  is 8

**Comment by maoyanting** [comment]
> `node -v` , please make sure the version of your node.js is 8

my current version id 8.4.0, but at first it was 12 until I find something wrong. 
I'm not familiar with node.js, maybe the reason is this.
