### ISSUE TITLE
http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html 文档中存在文字翻译错误问题

### ISSUE THREAD

**Issue by maslke** [apache/dubbo-website#470]
![TIM截图20190911094416](https://user-images.githubusercontent.com/6869592/64661904-17fb7e80-d479-11e9-8c86-94af2d528a53.png)

如上图所示，ConsumerConfig和ProducerConfig的中文意思反了。

**Comment by maslke** [comment]
http://dubbo.apache.org/zh-cn/docs/user/references/xml/dubbo-service.html
![1](https://user-images.githubusercontent.com/6869592/64662570-804b5f80-d47b-11e9-98ba-6f7de1eaa790.png)
上图中，中文描述应该是 缺省

**Comment by sonymoon** [comment]
Will you be pleasure to offer an PR?

**Comment by htynkn** [comment]
Close via #475
