### ISSUE TITLE
Poor Browser Leverage Caching

### ISSUE THREAD

**Issue by realabbas** [apache/dubbo-website#474]
I just ran a Page Speed test on http://dubbo.apache.org/ and found that it lacks browser caching.

![image](https://user-images.githubusercontent.com/43527087/65164446-8a142a80-da5a-11e9-8709-09bc86bbb7f0.png)

![image](https://user-images.githubusercontent.com/43527087/65164465-939d9280-da5a-11e9-8cee-8f3cd81f5577.png)

The page speed can be increased using **.htaccess file.** 
I can make the necessary changes and increase the page speed.

Page Report: https://gtmetrix.com/reports/dubbo.apache.org/LkB3zF1a

**Comment by htynkn** [comment]
because website is hosted in apache server, I'm not sure if it allow custom `.htaccess` for single project site. 
I'm trying to check if any other apache project website are using `.htaccess`

**Comment by htynkn** [comment]
I have tested and confirm `.htaccess` works for apache dubbo website server. 

What kind of changes do we need to increase the page speed?
If you want to send PR, please create .htacess file. I will modify deploy script to include it.

Thanks

**Comment by realabbas** [comment]
> I have tested and confirm `.htaccess` works for apache dubbo website server.
> 
> What kind of changes do we need to increase the page speed?
> If you want to send PR, please create .htacess file. I will modify deploy script to include it.
> 
> Thanks

Hey, thanks for the consideration. I have created a PR regarding the improvement of the Page Speed. Do check it. PR #483

**Comment by htynkn** [comment]
Close via #483.
