### ISSUE TITLE
关于文档中的错别字

### ISSUE THREAD

**Issue by Welxk** [apache/dubbo-website#490]
![image](https://user-images.githubusercontent.com/13851640/66285008-4d22b180-e8fd-11e9-9c7e-39897435ea68.png)
该出处在使用zk作为注册中心的说明的地方，存在笔误

**Comment by htynkn** [comment]
文档：https://dubbo.apache.org/zh-cn/docs/user/references/registry/zookeeper.html
能描述一下具体哪里建议修改吗？

**Comment by htynkn** [comment]
close via #494
