### ISSUE TITLE
用户文档中单词错误

### ISSUE THREAD

**Issue by Sossq** [apache/dubbo-website#497]
目录：用户文档-》配置-》属性配置
模块：重写与优先级
优先级从高到低列表第一项行尾dubbo单词拼写错误
![image](https://user-images.githubusercontent.com/10088599/66888279-7c79a280-f010-11e9-9297-f156a3ac95af.png)

**Comment by csxiaoshang** [comment]
你好，针对这个问题 你打算提PR吗？不的话，回头我提交个PR了

**Comment by lzf971107** [comment]
@Sossq 
Hello, this issue has been fixed, please check out #500

**Comment by lovepoem** [comment]
closed via https://github.com/apache/dubbo-website/pull/500
