### ISSUE TITLE
首页占用 20% CPU

### ISSUE THREAD

**Issue by wei345** [apache/dubbo-website#513]
首页背景动画，看起来挺有现代感。但是我电脑啥都没干，CPU 却占了 23%，罪魁祸首就是这个 Dubbo 首页。我想开发人员来首页都不是为了看动画的。注重性能的 Dubbo 占这么多 CPU 做用户不关心的事？

**Comment by htynkn** [comment]
是说这个动画吗？

<img width="1256" alt="首页" src="https://user-images.githubusercontent.com/659135/68194674-6435eb80-fff0-11e9-8de6-f8dae478f038.png">

能提供一下浏览器版本等相关信息吗？还是用的benchmark工具？我用chrome看了下没啥特别的占用

<img width="415" alt="任务2" src="https://user-images.githubusercontent.com/659135/68194772-98111100-fff0-11e9-9b81-771aa7715d5e.png">

<img width="477" alt="任务" src="https://user-images.githubusercontent.com/659135/68194610-4d8f9480-fff0-11e9-80d7-9f603fdf99b7.png">

**Comment by htynkn** [comment]
closing with no response for a long time
