### ISSUE TITLE
在dubbo的泛化调用介绍页面内部有一个demo 404

### ISSUE THREAD

**Issue by chlsmile** [apache/dubbo-website#550]
页面http://dubbo.apache.org/zh-cn/blog/dubbo-generic-invoke.html，上有一段介绍【本文中提到的相关示例代码可以在 dubbo-samples中找到：https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-generic】，其中的https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-generic 404了

**Comment by lzf971107** [comment]
@chlsmile 
Hello, I will fix this.
