### ISSUE TITLE
用户文档分组聚合的java源码示例超链接已经失效，示例仓库已经修改了路径！

### ISSUE THREAD

**Issue by shouge** [apache/dubbo-website#556]
#### 连接失效地址 
http://dubbo.apache.org/zh-cn/docs/user/demos/group-merger.html
 [原地址为: https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-merge](https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-merge) 示例仓库添加其他语言示例分类 路径已经发生变化[最新示例地址: https://github.com/apache/dubbo-samples/tree/master/java/dubbo-samples-merge](https://github.com/apache/dubbo-samples/tree/master/java/dubbo-samples-merge)

**Comment by lixiaojiee** [comment]
This issue has been resolved, I will close it now.
