### ISSUE TITLE
the articles in the blog of dubbo are loss

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo-website#581]
Issue source : apache/dubbo#6009

the following urls of articles are unable to access
1. "https://dubbo.apache.org/zh-cn/blog/grpc-http2-protobuf.html"
2. "https://dubbo.apache.org/blog/zh-cn/apche-dubbo-2019-2020.html"
3. "https://dubbo.apache.org/blog/zh-cn/2.7.5-release.html"

**Comment by AlbumenJ** [comment]
The place to find these urls

1. http://dubbo.apache.org/zh-cn/blog/index.html
![image](https://user-images.githubusercontent.com/9292748/79182616-cf0e0d00-7e41-11ea-882a-57d4b82b4d01.png)

2. http://dubbo.apache.org/zh-cn/docs/user/new-features-in-a-glance.html
![image](https://user-images.githubusercontent.com/9292748/79182685-fc5abb00-7e41-11ea-85df-d0bf191bff2e.png)

**Comment by AlbumenJ** [comment]
@htynkn The blog links in http://dubbo.apache.org/zh-cn/docs/user/new-features-in-a-glance.html still unable to access. Could you please fix it ?

**Comment by htynkn** [comment]
done. thanks for your feedback
