### ISSUE TITLE
http://start.dubbo.io/ 无法访问

### ISSUE THREAD

**Issue by wolf8334** [apache/dubbo-website#603]
使用Win 10，Chrome 83访问  http://start.dubbo.io/  时，系统500报错，截图如下。

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Jun 13 12:46:05 CST 2020
There was an unexpected error (type=Internal Server Error, status=500).
Could not determine version based on '2.4.0-SNAPSHOT': version format is Minor.Major.Patch.Qualifier (e.g. 1.0.5.RELEASE)

**Comment by agmtopy** [comment]
现在是这个网址了  https://start.aliyun.com/bootstrap.html
