### ISSUE TITLE
word error

### ISSUE THREAD

**Issue by tony-steven** [apache/dubbo-website#609]
https://dubbo.apache.org/en-us/docs/user/dependencies.html
Optinal dependencies ->Optional dependencies

**Comment by lovepoem** [comment]
Would you please send a pr ?

**Comment by tony-steven** [comment]
Sorry, I don't know what you mean, but you can search the words 'Optinal dependencies' in this page. https://dubbo.apache.org/en-us/docs/user/dependencies.html . The word 'Optinal' is error

**Comment by lovepoem** [comment]
意思是你提交代码来更正这个错误

tony steven <notifications@github.com> 于2020年7月31日周五 下午1:46写道：

**Comment by htynkn** [comment]
closed via https://github.com/apache/dubbo-website/pull/610
