### ISSUE TITLE
dubbo properties 配置不支持环境变量

### ISSUE THREAD

**Issue by carlyn2017** [apache/dubbo-website#612]
address: redis://${APP_REDIS_HOST:localhost}:${APP_REDIS_PORT:6379}

在application.properties里面做环境变量配置，不支持。

**Comment by htynkn** [comment]
我理解这个是想提交到dubbo仓库的。
这个支持应该是工作的，参考samples中的例子：https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-simplified-registry/dubbo-samples-simplified-registry-properties/src/main/resources/dubbo.properties

如果还有问题，请在https://github.com/apache/dubbo/issues 中提出
