### ISSUE TITLE
官网网站好多url返回404了。

### ISSUE THREAD

**Issue by minioreo** [apache/dubbo-website#636]
比如：

http://dubbo.apache.org/zh-cn/docs/user/references/telnet.html
http://dubbo.apache.org/zh-cn/docs/user/demos/thread-model.html
http://dubbo.apache.org/zh-cn/docs/user/demos/dump.html

上周还能访问的，这周开始都404了。这些链接都是google搜索点进去的。

**Comment by chickenlj** [comment]
The redirection is not working as expected, we will see what's going on.

**Comment by chickenlj** [comment]
The redirect problem has been fixed, please help to check.
