### ISSUE TITLE
官网上很多文章报404是什么原因

### ISSUE THREAD

**Issue by hhungry** [apache/dubbo-website#637]
比如开发手册下面的源码构建、框架设计

**Comment by chickenlj** [comment]
The redirect problem has been fixed, please help to check

**Comment by hhungry** [comment]
中文版 【开发手册】下面的文章跳转链接还是有问题，会直接跳转到首页

**Comment by htynkn** [comment]
> 中文版 【开发手册】下面的文章跳转链接还是有问题，会直接跳转到首页

fixed

**Comment by beiwei30** [comment]
fixed.
