### ISSUE TITLE
2.7版本目录:/user/demos/async-call/

### ISSUE THREAD

**Issue by ilovedumplings** [apache/dubbo-website#645]
重载一个带有CompletableFuture签名的方法 此处两个"带有",是否重复?

**Comment by htynkn** [comment]
url: https://dubbo.apache.org/zh/docs/v2.7/user/examples/async-call/
fixed:
![image](https://user-images.githubusercontent.com/659135/106223199-f04ab900-621b-11eb-861b-9010610f4247.png)
