### ISSUE TITLE
官网的源码导读部分有很多页面404

### ISSUE THREAD

**Issue by ZhangKe4042602** [apache/dubbo-website#648]
## Expected Behavior
https://dubbo.apache.org/zh-cn/docs/2.7/source_code_guide 下的文章能够显示

## Actual Behavior
最近这段时间官网升级导致源码导读下的文章404，目前只有《服务调用过程》，《SPI自适应扩展机制》两个是可以查看的。不知道是路径变更了还是怎么回事？

## Release Note

RELEASE NOTE:

**Comment by beiwei30** [comment]
http://dubbo.apache.org/zh/docs/v2.7/dev/source/  源码解读在这里

**Comment by ilovedumplings** [comment]
zh_cn路径下的都不行了,zh得行,但是感觉zh_cn路径下的界面更好看...(ˉ▽ˉ；)...

**Comment by zjcool** [comment]
> zh_cn路径下的都不行了,zh得行,但是感觉zh_cn路径下的界面更好看...(ˉ▽ˉ；)...

新的界面丑出天际，还不全，瞎搞
