### ISSUE TITLE
上下文信息

### ISSUE THREAD

**Issue by liuyalou1996** [apache/dubbo-website#666]
schema 配置参考手册：http://dubbo.apache.org/zh/docs/v2.7/user/references/xml/introduction
链接无效

**Comment by xiehaib** [comment]
Which page is this error link on

**Comment by dongzl** [comment]
Fixes by #715 .

**Comment by AlbumenJ** [comment]
close #666 via #715

如果其他页面仍有错误请重新开启此 issue
