### ISSUE TITLE
dubbo.apache.org/zh-ch cann't view

### ISSUE THREAD

**Issue by git-aking** [apache/dubbo-website#673]
dubbo.apache.org/zh-ch cann't view

**Comment by beiwei30** [comment]
try http://dubbo.apache.org/zh/

**Comment by git-aking** [comment]
thks--    发自新浪邮箱客户端
在 12月4日 13:22，Ian Luo <notifications@github.com> 写道：

try http://dubbo.apache.org/zh/

&mdash;
