### ISSUE TITLE
分组聚合

### ISSUE THREAD

**Issue by chennut0802** [apache/dubbo-website#732]
"dubbo 项目中的示例"这个链接无法正常打开，返回404.

**Comment by AlbumenJ** [comment]
@chennut0802 would you pls provide the url of which page contain invalid link

**Comment by chennut0802** [comment]
https://dubbo.apache.org/zh/docs/v2.7/user/examples/group-merger/ "dubbo 项目中的示例"这个链接无法正常打开，返回404.

**Comment by wangchengming666** [comment]
has been fixed in #931
