### ISSUE TITLE
Dubbo-Api-Docs -- Apache Dubbo文档展示

### ISSUE THREAD

**Issue by zhouxw536** [apache/dubbo-website#742]
对于DubboService设置了group的provider, docs里的注解好像未做支持？

**Comment by KeRan213539** [comment]
目前还不支持, 预计在 2.7.8.2 版本中支持
dubbo-api-docs 相关问题请提到 https://github.com/apache/dubbo-spi-extensions 或者 https://github.com/apache/dubbo-admin
这个issue我就先关了,相关问题在这个 issue中: https://github.com/apache/dubbo-spi-extensions/issues/19, 如果有什么疑问还请移步到这个issue中回复~

**Comment by KeRan213539** [comment]
目前还不支持, 预计在 2.7.8.2 版本中支持
dubbo-api-docs 相关问题请提到 https://github.com/apache/dubbo-spi-extensions 或者 https://github.com/apache/dubbo-admin
这个issue我就先关了,相关问题在这个 issue中: https://github.com/apache/dubbo-spi-extensions/issues/19, 如果有什么疑问还请移步到这个issue中回复~
