### ISSUE TITLE
实现泛化调用

### ISSUE THREAD

**Issue by spurstong** [apache/dubbo-website#752]
![image](https://user-images.githubusercontent.com/17487735/111066279-1d67d800-84f9-11eb-84a9-e146bfe68d7b.png)
泛化调用是不是用于服务消费端没有API的情况，而不是服务器端

**Comment by AlbumenJ** [comment]
服务端也可以有泛化实现，可以参考 https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-generic/dubbo-samples-generic-impl
