### ISSUE TITLE
Dubbo 源代码分析

### ISSUE THREAD

**Issue by nemofusion** [apache/dubbo-website#755]
本页面顺序与源码阅读顺序不太一致，比如
DUBBO SPI后应为服务目录
包含服务目录/服务路由/集群/负载均衡四项
但是服务路由跑到第二项了，看完SPI后看到服务路由有点蒙圈...
出来翻翻目录才发现这个目录错了，希望改正，谢谢！

**Comment by Justonly5** [comment]
确实如此。内容是有顺序的，但是目录上的顺序都不匹配，希望能调整下目录的顺序。感谢！

**Comment by wangchengming666** [comment]
@nemofusion 我测试了一下，应该是对应的上的呢
