### ISSUE TITLE
API 配置

### ISSUE THREAD

**Issue by LY1806620741** [apache/dubbo-website#759]
https://dubbo.apache.org/zh/docs/v2.7/user/configuration/api/ 中的
[配置参考手册](https://dubbo.apache.org/zh/docs/v2.7/user/configuration/references/xml/)链接无效

**Comment by LY1806620741** [comment]
应为 https://dubbo.apache.org/zh/docs/v2.7/user/references/xml/

**Comment by wangchengming666** [comment]
see #925
