### ISSUE TITLE
「Dubbo 中的 URL 统一模型」文档中，「公共契约」对应链接失效

### ISSUE THREAD

**Issue by EruDev** [apache/dubbo-website#761]
![微信截图_20210331161812](https://user-images.githubusercontent.com/31091355/113113410-de49be80-923c-11eb-8697-427909a2e743.png)
![微信截图_20210331161822](https://user-images.githubusercontent.com/31091355/113113568-06392200-923d-11eb-99aa-5c405b4d94ee.png)

**Comment by htynkn** [comment]
https://dubbo.apache.org/zh/docs/v2.7/dev/contract/
https://dubbo.apache.org/en/docs/v2.7/dev/contract/

**Comment by EruDev** [comment]
thanks
