### ISSUE TITLE
管理控制台安装

### ISSUE THREAD

**Issue by boengood** [apache/dubbo-website#778]
安装的dubbo-admin ，修改了nacos的配置，但始终找不到服务，

配置如下
`admin.registry.address=nacos://127.0.0.1:8848
admin.config-center=nacos://127.0.0.1:8848
admin.metadata-report.address=nacos://127.0.0.1:8848

admin.root.user.name=root
admin.root.user.password=root
#group
admin.registry.group=DEFAULT_GROUP
admin.config-center.group=DEFAULT_GROUP
admin.metadata-report.group=DEFAULT_GROUP

#session timeout, default is one hour
admin.check.sessionTimeoutMilli=3600000

#namespace used by nacos
admin.registry.namespace=public
admin.config-center.namespace=public
admin.metadata-report.namespace=public
`

**Comment by KeRan213539** [comment]
https://github.com/apache/dubbo-admin/issues/628
