### ISSUE TITLE
Dubbo3 应用级服务发现 图片显示问题

### ISSUE THREAD

**Issue by fffscd** [apache/dubbo-website#843]
文档地址 https://dubbo.apache.org/zh/blog/2021/06/02/dubbo3-%E5%BA%94%E7%94%A8%E7%BA%A7%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0/
图片无法正常显示，我看图片是被定向到 https://intranetproxy.alipay.com/skylark/lark/0/2020/png/54037/1590152557149-ea956a69-f303-4c0e-b098-89ed61caf30b.png

![image](https://user-images.githubusercontent.com/4598330/123574975-68390180-d803-11eb-9840-61bce0670da1.png)

**Comment by dongzl** [comment]
看了一下图片地址，可能是阿里内部的图片链接，外网访问不到

**Comment by fffscd** [comment]
是的，是否考虑修复下呢

**Comment by fffscd** [comment]
是的，是否考虑修复下呢？毕竟这个网站是对外的

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo-website/pull/860
