### ISSUE TITLE
API 配置

### ISSUE THREAD

**Issue by csxiaoshang** [apache/dubbo-website#903]
![image](https://user-images.githubusercontent.com/20570530/130325317-b5827a52-b0ce-49ac-a5de-f1b62c5e4705.png)
![image](https://user-images.githubusercontent.com/20570530/130325334-ac4bf3ae-432e-4d7b-ab93-b594e3e6cecc.png)
**There is a problem with the link here.**

**Comment by wangchengming666** [comment]
I'll fix it
