### ISSUE TITLE
Page update commit links don't work

### ISSUE THREAD

**Issue by sebbASF** [apache/dubbo-website#968]
Many of the docs pages have 'Last updated:' footers with a link to what appears to be the relevant commit.

For example:
https://dubbo.apache.org/en/docs/contribution-guidelines/
has the footer:

Last modified August 27, 2021: 
<a href=/commit/1e4a72edd40ed727f33d6425c3560dc85f406f70>[DOC] Add meta-type parameter for dubbo:application (#920) (1e4a72e)</a>

However this link does not work.

P.S. The href value should be enclosed in quotes.

**Comment by danielamorais** [comment]
I verified and I didn't find any footer with "Last updated" in the documentation section

**Comment by sebbASF** [comment]
It looks like the footers have been dropped
