### ISSUE TITLE
应用级地址发现迁移指南

### ISSUE THREAD

**Issue by syshenyao** [apache/dubbo-website#988]
dubbo.application.register-mode 默认值是interface还是all？

**Comment by wangchengming666** [comment]
缺省值是instance

**Comment by AlbumenJ** [comment]
默认是 all

**Comment by AlbumenJ** [comment]
see https://github.com/apache/dubbo/blob/04a983792ad479efdc404bdcb600fddbd072820e/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java#L250

**Comment by syshenyao** [comment]
OK,Thank you!
